export const RESTART_FILTERS = "REMOVE_FILTERS";

export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";

export const FILTER_BY_CONTINENT = "FILTER_BY_ACTIVITY";

export const SORT_BY_POPULATION = "SORT_BY_POPULATION";

export const SORT_ASC = "SORT_ASC";

export const SORT_DESC = "SORT_DESC";

export const GET_COUNTRIES = "GET_COUNTRIES";

export const GET_CONTINENTS = "GET_CONTINENTS";

export const SEARCH_COUNTRIES = "SEARCH_COUNTRIES";

export const SET_LOADING = "SET_LOADING";

export const CREATE_ACTIVITY = "CREATE_ACTIVITY";